shared:
  ingress_domain: " hn.tap.com"

ceip_policy_disclosed: true

#The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

#Below are the keys which may have default values set, but can be overridden.

profile: full # Can take iterate, build, run, view.

excluded_packages:
- policy.apps.tanzu.vmware.com

supply_chain: basic # Can take testing, testing_scanning.

ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: 729418097271.dkr.ecr.us-east-2.amazonaws.com
    # The prefix of the ECR repository.  Workloads will need
    # two repositories created:
    #
    # tanzu-application-platform/<workloadname>-<namespace>
    # tanzu-application-platform/<workloadname>-<namespace>-bundle
    repository: tanzu-application-platform

# contour:
#   envoy:
#     service:
#       type: LoadBalancer # This is set by default, but can be overridden by setting a different value.
contour:
  infrastructure_provider: aws
  envoy:
    service:
      aws:
        LBType: nlb

buildservice:
  kp_default_repository: 729418097271.dkr.ecr.us-east-2.amazonaws.com/tap-build-service
  # Enable the build service k8s service account to bind to the AWS IAM Role
  kp_default_repository_aws_iam_role_arn: "arn:aws:iam::729418097271:role/tap-build-service"
  #exclude_dependencies: true

ootb_templates:
  # Enable the config writer service to use cloud based iaas authentication
  # which are retrieved from the developer namespace service account by
  # default
  iaas_auth: true

tap_gui:
# Existing tap-values.yaml above
  app_config:
    app:
      baseUrl: http://tap-gui.hn.tap.com # No port needed with Ingress
    integrations:
      github: # Other are integrations available
        - host: github.com
          token: GITHUB-TOKEN
    catalog:
      locations:
        - type: url
          target: https://github.com/sample-accelerators/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.hn.tap.com # No port needed with Ingress
      cors:
        origin: http://tap-gui.hn.tap.com # No port needed with Ingress
# tap_gui:
#   service_type: LoadBalancer
#   app_config:
#     catalog:
#       locations:
#         - type: url
#           target: https://gui.hn.tap/catalog-info.yaml

metadata_store:
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

scanning:
  metadataStore:
    url: "" # Configuration is moved, so set this string to empty.

# tap_telemetry:
#   customer_entitlement_account_number: "CUSTOMER-ENTITLEMENT-ACCOUNT-NUMBER" # (Optional) Identify data for creating Tanzu Application Platform usage reports.
